<a href="https://colab.research.google.com/github/aimlresearcher/PyTorch101/blob/main/001_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the PyTorch library
import torch

# Print the version of the installed PyTorch library
print(torch.__version__)

2.3.1+cu121


In [2]:
# Retrieve and return the current default data type used by PyTorch tensors
torch.get_default_dtype()

torch.float32

In [3]:
# Set the default data type for PyTorch tensors to 64-bit integer (int64)
torch.set_default_dtype(torch.int64)

TypeError: only floating-point types are supported as the default type

In [4]:
# Set the default data type for PyTorch tensors to 64-bit floating point (float64)
torch.set_default_dtype(torch.float64)

In [5]:
# Retrieve and return the current default data type used by PyTorch tensors
torch.get_default_dtype()

torch.float64

In [6]:
# Create a 2D tensor with the specified values using the default data type
tensor_arr = torch.Tensor([[1, 2, 3], [4, 5, 6]])

# Display the created tensor
tensor_arr


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
# Check if the variable 'tensor_arr' is a tensor and return a boolean value
torch.is_tensor(tensor_arr)


True

In [8]:
# Return the total number of elements in the tensor 'tensor_arr'
torch.numel(tensor_arr)

6

In [9]:
# Create an uninitialized 2x2 tensor with the default data type
tensor_uninitialized = torch.Tensor(2, 2)

# Display the uninitialized tensor
tensor_uninitialized

tensor([[6.6115e-310, 6.6115e-310],
        [1.5810e-322, 3.1620e-322]])

In [10]:
# Create a 2x2 tensor with random values uniformly distributed between 0 and 1
tensor_initialized = torch.rand(2, 2)

# Display the initialized tensor with random values
tensor_initialized

tensor([[0.5034, 0.5261],
        [0.8064, 0.7739]])

In [11]:
# Create a tensor with the specified values and explicitly set its data type to 32-bit integer (IntTensor)
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)

# Display the tensor with integer values
tensor_int

tensor([5, 3], dtype=torch.int32)

In [12]:
# Create a tensor with the specified floating-point values and set its data type to 16-bit integer (ShortTensor)
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])

# Display the tensor with values converted to 16-bit integers
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [13]:
# Create a tensor with the specified floating-point values and explicitly set its data type to 16-bit floating point (half precision)
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)

# Display the tensor with values in half precision
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [14]:
# Create a 2x6 tensor where all elements are initialized to the value 10
tensor_fill = torch.full((2, 6), fill_value=10)

# Display the tensor with all elements set to 10
tensor_fill


tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [15]:
# Create a 2x4 tensor where all elements are initialized to 1, with data type set to 32-bit integer (int32)
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)

# Display the tensor with all elements set to 1
tensor_of_ones


tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [16]:
# Create a tensor of the same shape and data type as 'tensor_of_ones', but with all elements initialized to 0
tensor_of_zeroes = torch.zeros_like(tensor_of_ones)

# Display the tensor with all elements set to 0
tensor_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [17]:
# Create a 5x5 identity matrix with ones on the diagonal and zeros elsewhere
tensor_eye = torch.eye(5)

# Display the identity matrix
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
# Find the indices of non-zero elements in the 'tensor_eye' tensor
non_zero = torch.nonzero(tensor_eye)

# Display the indices of non-zero elements in the tensor
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [19]:
# Create a 2x3 tensor with the specified integer values
i = torch.tensor([[0, 1, 1],
                  [2, 2, 0]])

# Display the tensor 'i'
i

tensor([[0, 1, 1],
        [2, 2, 0]])

In [20]:
# Create a 1D tensor with the specified floating-point values and set the data type to 32-bit floating point (float32)
v = torch.tensor([3, 4, 5], dtype=torch.float32)

# Display the tensor 'v'
v

tensor([3., 4., 5.], dtype=torch.float32)

In [21]:
# Create a sparse tensor using COO (Coordinate) format with the given indices 'i', values 'v', and size [2, 5]
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])

# Access and display the data of the sparse tensor
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [22]:
# Create a 2x3 tensor with random values uniformly distributed between 0 and 1
initial_tensor = torch.rand(2, 3)

# Display the tensor with random values
initial_tensor


tensor([[0.1361, 0.9663, 0.1164],
        [0.8693, 0.4011, 0.7890]])

In [23]:
# Fill all elements of the 'initial_tensor' with the value 10
initial_tensor.fill_(10)

# Display the tensor after filling it with 10s
initial_tensor


tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [24]:
# Create a new tensor by adding 5 to each element of 'initial_tensor'
new_tensor = initial_tensor.add(5)

# Display the new tensor with updated values
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [25]:
# Display the original 'initial_tensor' to show it has not been modified by the addition operation
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [26]:
# In-place addition: add 8 to each element of 'initial_tensor' and modify it directly
initial_tensor.add_(8)

# Display the updated 'initial_tensor' with the added values
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [27]:
# Display 'new_tensor' to show it remains unchanged after modifying 'initial_tensor'
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [28]:
# In-place operation: compute the square root of each element in 'new_tensor' and modify it directly
new_tensor.sqrt_()

# Display the updated 'new_tensor' with square root values
new_tensor


tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [29]:
# Create a 1D tensor with 15 equally spaced values between 0.1 and 10.0
x = torch.linspace(start=0.1, end=10.0, steps=15)

# Display the tensor 'x' with the generated values
x


tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [30]:
# Split the tensor 'x' into 3 chunks along the specified dimension (0)
tensor_chunk = torch.chunk(x, 3, 0)

# Display the list of tensors resulting from the chunk operation
tensor_chunk


(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [31]:
# Access the first chunk from 'tensor_chunk'
tensor1 = tensor_chunk[0]

# Access the second chunk from 'tensor_chunk'
tensor2 = tensor_chunk[1]

# Create a new tensor with specified values
tensor3 = torch.tensor([3.0, 4.0, 5.0])

# Concatenate 'tensor1', 'tensor2', and 'tensor3' along dimension 0
torch.cat((tensor1, tensor2, tensor3), 0)


tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [32]:
# Create a 3x3 tensor with the specified integer values
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])

# Display the tensor 'random_tensor'
random_tensor


tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [33]:
# Access the element at the first row and second column of 'random_tensor'
random_tensor[0, 1]


tensor(8.)

In [34]:
# Access a sub-tensor of 'random_tensor' starting from the second row and second column to the end
random_tensor[1:, 1:]


tensor([[ 5.,  6.],
        [ 2., 21.]])

In [35]:
# Split the tensor 'random_tensor' into chunks of size 2 along the first dimension
random_tensor_split = torch.split(random_tensor, 2)

# Display the list of tensors resulting from the split operation
random_tensor_split


(tensor([[10.,  8., 30.],
         [40.,  5.,  6.]]),
 tensor([[12.,  2., 21.]]))

In [36]:
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [37]:
# Return the size of 'random_tensor'
random_tensor.size()


torch.Size([3, 3])

In [38]:
# Reshape 'random_tensor' to a 1D tensor with 9 elements
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [39]:
# Attempt to reshape 'random_tensor' to a 2D tensor with 6 columns (which is not possible for the current tensor)
resized_tensor = random_tensor.view(-1, 6)
resized_tensor

RuntimeError: shape '[-1, 6]' is invalid for input of size 9

In [40]:
# Display the size of the 'resized_tensor' to verify the reshaping operation
resized_tensor.size()


torch.Size([9])

In [41]:
# Modify the original tensor by setting the value at position (2, 2) to 100.0
random_tensor[2, 2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [42]:
# Add a new dimension to 'random_tensor' at position 2
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [43]:
# Display the shape of the tensor after adding a new dimension
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [44]:
# Transpose 'initial_tensor' by swapping dimensions 0 and 1
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [45]:
# Sort 'random_tensor' along the last dimension and obtain sorted values and their indices
sorted_tensor, sorted_indices = torch.sort(random_tensor)


In [46]:
# Display the sorted tensor
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [47]:
# Display the indices of the sorted values
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [48]:
# Create a tensor with specified floating-point values
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [49]:
# Compute the absolute values of 'tensor_float'
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [50]:
# Add 2 to each element of 'initial_tensor' and return a new tensor
new_tensor = torch.add(initial_tensor, 2)
new_tensor

tensor([[20., 20., 20.],
        [20., 20., 20.]])

In [51]:
# Perform an out-of-place addition of 10 to 'initial_tensor' and store the result in 'new_tensor'
torch.add(initial_tensor, 10, new_tensor)

<ipython-input-51-58883ebc95bd>:2: UserWarning: This overload of add is deprecated:
	add(Tensor input, Number alpha, Tensor other, *, Tensor out)
Consider using one of the following signatures instead:
	add(Tensor input, Tensor other, *, Number alpha, Tensor out) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1578.)
  torch.add(initial_tensor, 10, new_tensor)


tensor([[218., 218., 218.],
        [218., 218., 218.]])

In [52]:
# Generate two random tensors and compute their element-wise absolute values
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

# Perform element-wise addition of 'rand1' and 'rand2'
add1 = rand1 + rand2
add1

tensor([[0.7305, 1.9855, 0.2876],
        [2.9318, 2.3365, 1.7278]])

In [53]:
# Perform element-wise addition of 'rand1' and 'rand2' using the torch.add method
add2 = torch.add(rand1, rand2)
add2

tensor([[0.7305, 1.9855, 0.2876],
        [2.9318, 2.3365, 1.7278]])

In [54]:
# Create a tensor with specified integer values
tensor = torch.Tensor([[-1, -2, -3], [1, 2, 3]])

# Perform element-wise division of 'tensor' by itself with an added small value (0.3)
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [55]:
# Perform element-wise multiplication of 'tensor' by itself
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [56]:
# Clamp the values of 'tensor' to be within the range [-0.2, 2]
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [57]:
# Create two 1D tensors
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

# Compute the dot product of 't1' and 't2'
dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

In [58]:
# Create a 2x3 matrix and a 1D vector
matrix = torch.Tensor([[1, 2, 3], [4, 5, 6]])
vector = torch.Tensor([0, 1, 2])

# Compute the matrix-vector product of 'matrix' and 'vector'
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

In [59]:
# Create another 2x2 matrix
another_matrix = torch.Tensor([[10, 30], [20, 0], [0, 50]])

# Compute the matrix multiplication of 'matrix' and 'another_matrix'
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

In [60]:
# Find the indices of the maximum values along dimension 1 of 'matrix_mul'
torch.argmax(matrix_mul, dim=1)


tensor([1, 1])

In [61]:
# Find the indices of the minimum values along dimension 1 of 'matrix_mul'
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])